# Generated by Django 5.1.6 on 2025-02-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spatial_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="point",
            name="extra_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="polygon",
            name="extra_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
